# Generated by Django 5.2.10 on 2026-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('accuracy_score', models.FloatField()),
                ('last_trained', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millet_type', models.CharField(choices=[('ragi', 'Ragi'), ('jowar', 'Jowar'), ('bajra', 'Bajra'), ('foxtail', 'Foxtail'), ('proso', 'Proso'), ('little', 'Little')], max_length=20)),
                ('month', models.IntegerField(verbose_name='Month (1-12)')),
                ('location', models.CharField(max_length=100)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sales Histories',
            },
        ),
    ]
