# Generated by Django 5.2.10 on 2026-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform Administrator'), ('farmer', 'Millet Producer (Farmer)'), ('buyer', 'Millet Consumer (Buyer)')], default='farmer', max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
