# Generated by Django 5.2.10 on 2026-03-01 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilletProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millet_type', models.CharField(choices=[('ragi', 'Ragi (Finger Millet)'), ('jowar', 'Jowar (Sorghum)'), ('bajra', 'Bajra (Pearl Millet)'), ('foxtail', 'Foxtail Millet'), ('proso', 'Proso Millet'), ('little', 'Little Millet')], max_length=20, verbose_name='Millet Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilograms (kg)'), ('quintal', 'Quintal')], default='kg', max_length=10, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Price (per unit)')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Product Image')),
                ('description', models.TextField(blank=True, verbose_name='Additional Details')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Millet Product',
                'verbose_name_plural': 'Millet Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
